import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { UserProvider } from '@auth0/nextjs-auth0/client';

import ThemeRegistry from '@/components/ThemeRegistry/ThemeRegistry'; //generate ui issues
import AppBar from '@/components/AppBar';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* <ThemeRegistry> */}
      <UserProvider>
        <body className={inter.className}>
          <AppBar />
          {children}
        </body>
      </UserProvider>
      {/* </ThemeRegistry> */}
    </html>
  );
}
